### ISSUE TITLE
Redis Module support

### ISSUE THREAD

**Issue by rohitchormale** [fiorix/txredisapi#124]
Thanks for this great lib. 
Does txredisapi support _module_ feature added in _redis > 4.0_ ? 
I am specifically looking for [redisSQL](https://github.com/RedBeardLab/rediSQL) support.

**Comment by IlyaSkriblovsky** [comment]
txredisapi has explicit support only for Redis's native commands. But I beleive you can use rediSQL commands like this:
```python
rows = yield connection.execute_command("REDISQL.EXEC", "DB", "SELECT * FROM foo;")
```

Please let us know whether it will work if you will try it.

**Comment by rohitchormale** [comment]
thanks for info. I will update you soon

**Comment by rohitchormale** [comment]
It is working like you mentioned.

**Comment by IlyaSkriblovsky** [comment]
Cool!
