### ISSUE TITLE
Not honoring timeout setting

### ISSUE THREAD

**Issue by rohitchormale** [fiorix/txredisapi#130]
First of all, thanks for great project. 
I am recently ended up using sentinel. But txredisapi is losing connection frequently and trying to reconnect. 

My code is something like this
```
    sentinel = txredisapi.Sentinel(sentinel_addresses=[("foo", 26379), ("bar", 26380), ("baz", 26381)], convertNumbers=False)
    redis = sentinel.master_for("my-cluster")

```
Below are logs
> Starting factory <txredisapi.RedisFactory instance at 0x7f33d1f64200>
<twisted.internet.tcp.Connector instance at 0x7f33d1f64320> will retry in 9 seconds
Stopping factory <txredisapi.RedisFactory instance at 0x7f33d1f64200>
Starting factory <txredisapi.RedisFactory instance at 0x7f33d1f64680>
<twisted.internet.tcp.Connector instance at 0x7f33d1f647a0> will retry in 8 seconds
Stopping factory <txredisapi.RedisFactory instance at 0x7f33d1f64680>
Starting factory <txredisapi.RedisFactory instance at 0x7f33d1f64200>
Starting factory <txredisapi.RedisFactory instance at 0x7f33d1f64680>
<twisted.internet.tcp.Connector instance at 0x7f33d1f647a0> will retry in 9 seconds
Stopping factory <txredisapi.RedisFactory instance at 0x7f33d1f64680>

 There is very old [question](https://stackoverflow.com/questions/15969588/redis-disconnecting-and-reconnecting-on-twisted-periodically) related to this on stack over flow. But the accepted solution is not working. timeout value in redis.conf is 0 by default.

 If I use lazyConnectionPool without sentinel, it works well. I am able to reproduce this issue on 3.2.8 and 4.0.9 version.

Any help will be appreciated. Thanks.

**Comment by rohitchormale** [comment]
When I execute query, I am getting result. But once the execution is finished, client is trying to reconnect.

**Comment by IlyaSkriblovsky** [comment]
Are you sure you have all your sentinel nodes up and responding? Such messages may indicate that txrediapi can't connect to one of the sentinels.

**Comment by rohitchormale** [comment]
It seems like that. Sentinel nodes are up but I am not able to connect one of them remotely. After fixing iptables it worked. I will dig more and will update you soon. thanks again.

**Comment by rohitchormale** [comment]
@IlyaSkriblovsky indeed it was the reason. I really appreciate your quick response. Спасибо !

**Comment by IlyaSkriblovsky** [comment]
@rohitchormale Всегда пожалуйста!
