### ISSUE TITLE
Number types in hgetall not always equal to hmset.

### ISSUE THREAD

**Issue by jonathanslenders** [fiorix/txredisapi#37]
I cannot tell whether the bug in in txredisapi, in redis or our code.

 # Set the value '4', as a string in this hash mapping
 redis.hmset('key', {  "a": "4" })

 # Retrieve the hash again.
 redis.hgetall('key')

This returns { "a": 4}, so the string turned to an integer.

**Comment by iksteen** [comment]
Any chance of this getting another look? I've commented out the magic casting code in a local copy because we work with `decimal.Decimal` so interpreting the string value using `float()` is a no-go for us. IMO, 'magic' behaviour is pretty undesirable for a low-level database driver.

**Comment by fiorix** [comment]
Sure, send a patch and I'll review. Even if it breaks backwards compatibility (which I think it will) we can debate about how to fix it properly.

**Comment by fiorix** [comment]
Perfect @jeethu. Now the magic is optional.
