### ISSUE TITLE
SubscriberProtocol hangs when password is set on factory

### ISSUE THREAD

**Issue by minus7** [fiorix/txredisapi#85]
SubscriberProtocol.replyReceived swallows the "OK" reply for the AUTH command, causing factory.deferred never to be completed, thus not giving the connection to the user.
If authentication is enabled, AUTH is necessary to to subscribe. MonitorProtocol probably has the same issue. A dbid being set causes the same problem. Of course, SELECTing a DB does not make sense when using SubscriberProtocol, but in my case happened because I reused connection credentials from a "data" connection.

A quick fix that seems to work is to add an else clause to replyReceived:
```python
        else:
            self.replyQueue.put(reply)
```

Example:
```python
from twisted.internet import defer, reactor
from txredisapi import SubscriberProtocol, RedisFactory

@defer.inlineCallbacks
def main():
	factory = RedisFactory(None, dbid=None, poolsize=1, password="test")
	factory.protocol = SubscriberProtocol
	reactor.connectTCP("localhost", 6379, factory)
	print("Connecting...")
	conn = yield factory.deferred
	print("Connected.")
	yield conn.subscribe("test")
	print("Subscribed.")

main()
reactor.run()
```

**Comment by fiorix** [comment]
I'd be great if you could provide the patch and a test case.

**Comment by minus7** [comment]
Done :)
The test case was a bit tricky because it kind of requires a password being set on Redis, I hope it's fine the way I did it.
I didn't write a test for MonitorProtocol, since there wasn't any test yet.
