### ISSUE TITLE
what would be the estimated effort for Python 3 compatibility?

### ISSUE THREAD

**Issue by xihan** [fiorix/txredisapi#87]
Since twistedpy now is working with python 3.4, I wonder how much effort it would be to make this project also py3 compatible.

I noticed mainly two things:
  (1) except Exception, e
  (2) str vs byte

I'm not asking anyone to do the work, just curious if someone has an idea if this is hard.
I can educate myself about writing py2/3 compatible code and help as well.

Thanks!

**Comment by fiorix** [comment]
Question would be what's the status of Python 3 and Twisted. I haven't touched any of this in a while and have no desire to do so. In fact I gave up on Python because of this messed up transition from 2 to 3.

**Comment by dpkp** [comment]
With a good unit test suite like txredisapi has, I dont think it would be terribly difficult.  Rely on `six` for handling the details and it usually goes quickly.

**Comment by xihan** [comment]
Thanks fiorix, dpkg for the information.

I will study six (and how other libs use it) and try my best to contribute.

xihan
